package webui

import (
	"embed"
	"io/fs"
)

// distappFS contains bundled frontend artifacts generated by web/build.mjs.
//
//go:embed distapp/**
var distappFS embed.FS

func DistFS() (fs.FS, error) {
	return fs.Sub(distappFS, "distapp")
}
